// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkFT1HeufS2AowG8JuBgiZ6Z6fwLgQpxk',
    appId: '1:863358238289:web:8873cabefdd63a04bfc270',
    messagingSenderId: '863358238289',
    projectId: 'fir-recipes-app-a0c2c',
    authDomain: 'fir-recipes-app-a0c2c.firebaseapp.com',
    storageBucket: 'fir-recipes-app-a0c2c.firebasestorage.app',
    measurementId: 'G-75WWKS9M2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vUsSq29CEUrgrySNfK7_553ZacG5BQk',
    appId: '1:863358238289:android:26f859dc99bec1d7bfc270',
    messagingSenderId: '863358238289',
    projectId: 'fir-recipes-app-a0c2c',
    storageBucket: 'fir-recipes-app-a0c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlPwjKfI7yexaQFXGDQYzlBuAc4caeBw',
    appId: '1:863358238289:ios:228ff59da299c906bfc270',
    messagingSenderId: '863358238289',
    projectId: 'fir-recipes-app-a0c2c',
    storageBucket: 'fir-recipes-app-a0c2c.firebasestorage.app',
    iosBundleId: 'com.example.recepiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlPwjKfI7yexaQFXGDQYzlBuAc4caeBw',
    appId: '1:863358238289:ios:228ff59da299c906bfc270',
    messagingSenderId: '863358238289',
    projectId: 'fir-recipes-app-a0c2c',
    storageBucket: 'fir-recipes-app-a0c2c.firebasestorage.app',
    iosBundleId: 'com.example.recepiesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkFT1HeufS2AowG8JuBgiZ6Z6fwLgQpxk',
    appId: '1:863358238289:web:e81a7e49710a4cabbfc270',
    messagingSenderId: '863358238289',
    projectId: 'fir-recipes-app-a0c2c',
    authDomain: 'fir-recipes-app-a0c2c.firebaseapp.com',
    storageBucket: 'fir-recipes-app-a0c2c.firebasestorage.app',
    measurementId: 'G-YTY0YK7Y0D',
  );
}
